server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/search_engine
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.svetlovka.ru/
      name: Svetlovka.ru
